In [272]:
# ============================================
# IMPORTACIÓN DE LIBRERÍAS NECESARIAS
# ============================================

# Librerías para manipulación y análisis de datos
import pandas as pd  # Pandas: trabajar con DataFrames y series de datos
import numpy as np   # NumPy: operaciones matemáticas y arrays numéricos

# Librerías para visualización de datos
import matplotlib as plt  # Matplotlib: crear gráficos básicos
import seaborn as sns     # Seaborn: gráficos estadísticos más avanzados

# Librerías de scikit-learn para Machine Learning
from sklearn.model_selection import train_test_split  # Dividir datos en entrenamiento y test
from sklearn.preprocessing import PolynomialFeatures, StandardScaler, MinMaxScaler  # Transformar features
from sklearn.linear_model import LinearRegression, Ridge, Lasso  # Modelos de regresión lineal
from sklearn.metrics import mean_absolute_error, mean_squared_error  # Métricas para evaluar modelos

In [273]:
# ============================================
# CARGA DE DATOS DE LA COMPETICIÓN DE KAGGLE
# ============================================

# Cargamos el conjunto de entrenamiento (contiene la columna objetivo Price_euros)
df = pd.read_csv('./data/train.csv')

# Cargamos el conjunto de test (NO contiene Price_euros, debemos predecirlo)
test = pd.read_csv('./data/test.csv')

# Cargamos el archivo de ejemplo para saber el formato correcto del submission
sample = pd.read_csv('./data/sample_submission.csv')

In [274]:
df.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,268,1002,Dell,Inspiron 5567,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,AMD Radeon R7 M445,Windows 10,2.36kg,749.00
1,347,867,Asus,X541NA (N4200/4GB/1TB/W10),Notebook,15.6,1366x768,Intel Pentium Quad Core N4200 1.1GHz,4GB,1TB HDD,Intel HD Graphics 505,Windows 10,2kg,449.00
2,353,966,Toshiba,Portege Z30-C-1CW,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.2kg,1460.00
3,578,767,Dell,Alienware 17,Gaming,15.6,IPS Panel 4K Ultra HD 3840x2160,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,Windows 10,4.42kg,2868.99
4,42,1241,Dell,Latitude E7270,Ultrabook,12.5,Full HD / Touchscreen 1920x1080,Intel Core i5 6300U 2.4GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.26kg,1713.37

In [275]:
test

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,181,1098,HP,Spectre x360,Ultrabook,13.3,IPS Panel 4K Ultra HD 3840x2160,Intel Core i7 7500U 2.7GHz,16GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.3kg
1,708,330,Acer,Aspire 5,Notebook,15.6,1366x768,AMD A12-Series 9720P 2.7GHz,8GB,256GB SSD,AMD Radeon RX 540,Windows 10,2.2kg
2,862,1260,Acer,Aspire ES1-572,Notebook,15.6,1366x768,Intel Core i3 6006U 2.0GHz,4GB,500GB HDD,Intel HD Graphics 520,Linux,2.4kg
3,1064,1137,HP,EliteBook 1040,Notebook,14.0,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.43kg
4,702,1015,HP,ENVY -,Notebook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.34kg
...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,1281,145,Lenovo,Legion Y520-15IKBN,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8GB,256GB SSD,Nvidia GeForce GTX 1050M,No OS,2.4kg
387,524,1195,Lenovo,IdeaPad Y700-15ISK,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,16GB,512GB SSD,Nvidia GeForce GTX 960,Windows 10,3.31kg
388,1015,1070,HP,250 G5,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,No OS,1.96kg
389,1236,104,HP,15-bw000nv (E2-9000e/4GB/500GB/Radeon,Notebook,15.6,Full HD 1920x1080,AMD E-Series E2-9000e 1.5GHz,4GB,500GB HDD,AMD Radeon R2,Windows 10,2.1kg
390,1036,258,Lenovo,Yoga 920-13IKB,2 in 1 Convertible,13.9,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 8550U 1.8GHz,8GB,512GB SSD,Intel UHD Graphics 620,Windows 10,1.37kg

In [276]:
sample.head()

     id  Price_euros
0  1014        752.0
1   845        499.0
2  1151       1747.0
3  1265        245.0
4   573       1179.0

In [277]:
sample[sample['id']==268]

Empty DataFrame
Columns: [id, Price_euros]
Index: []

In [278]:
sample[sample['id']==181]

     id  Price_euros
25  181       465.62

In [279]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                912 non-null    int64
 1   laptop_ID         912 non-null    int64
 2   Company           912 non-null    object
 3   Product           912 non-null    object
 4   TypeName          912 non-null    object
 5   Inches            912 non-null    float64
 6   ScreenResolution  912 non-null    object
 7   Cpu               912 non-null    object
 8   Ram               912 non-null    object
 9   Memory            912 non-null    object
 10  Gpu               912 non-null    object
 11  OpSys             912 non-null    object
 12  Weight            912 non-null    object
 13  Price_euros       912 non-null    float64
dtypes: float64(2), int64(2), object(10)
memory usage: 99.9+ KB

In [280]:
df['Company'].value_counts()

Company
Lenovo       208
Dell         207
HP           189
Asus         108
Acer          75
Toshiba       37
MSI           34
Apple         17
Mediacom       7
Razer          6
Samsung        6
Fujitsu        3
Microsoft      3
Vero           3
Xiaomi         3
Chuwi          2
Google         2
LG             1
Huawei         1
Name: count, dtype: int64

In [281]:
df['Product'].value_counts()

Product
Inspiron 3567                                21
XPS 13                                       20
250 G6                                       19
Vostro 3568                                  16
ProBook 450                                  11
                                             ..
GL62M (i5-7300HQ/8GB/1TB                      1
Omen 17-W295                                  1
EliteBook Folio                               1
X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux)     1
Probook 640                                   1
Name: count, Length: 475, dtype: int64

In [282]:
df[df['Product'] == 'Inspiron 3567']

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
46,1047,26,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i3 6006U 2GHz,4GB,1TB HDD,Intel HD Graphics 520,Windows 10,2.3kg,418.64
161,1023,98,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,AMD Radeon R5 M430,Linux,2.2kg,599.90
262,1238,422,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,AMD Radeon R5 M430,Linux,2.3kg,598.90
320,929,1285,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,AMD Radeon R5 M430,Linux,2.3kg,805.99
363,890,425,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,8GB,1TB HDD,Intel HD Graphics 620,Windows 10,2.14kg,539.95
369,1142,535,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,AMD Radeon R5 M430,Windows 10,2.3kg,585.00
378,1191,586,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,256GB SSD,AMD Radeon R5 M430,Linux,2.2kg,749.01
410,913,1299,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,AMD Radeon R5 M430,Linux,2.3kg,805.99
447,1157,99,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,256GB SSD,AMD Radeon R5 M430,Linux,2.2kg,485.00
459,955,14,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.2kg,498.90
590,270,695,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i3 6006U 2GHz,4GB,1TB HDD,AMD Radeon R5 M430,Windows 10,2.2kg,545.67
611,455,1250,Dell,Inspiron 3567,Notebook,15.6,Touchscreen 1366x768,Intel Core i3 7100U 2.4GHz,8GB,1TB HDD,Intel HD Graphics 620,Windows 10,2.3kg,469.01
626,815,1294,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i3 7100U 2.4GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows 10,2.3kg,459.00
660,37,1280,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i3 7100U 2.4GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows 10,2.3kg,459.00
746,101,1308,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i3 7100U 2.4GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows 10,2.3kg,459.00
784,995,364,Dell,Inspiron 3567,Notebook,15.6,Touchscreen 1366x768,Intel Core i5 7200U 2.5GHz,8GB,2TB HDD,Intel HD Graphics 620,Windows 10,2.36kg,557.37
801,246,269,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,1TB HDD,AMD Radeon R5 M430,Windows 10,2.24kg,565.00
820,1272,210,Dell,Inspiron 3567,Notebook,15.6,Touchscreen 1366x768,Intel Core i3 7100U 2.4GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows 10,2.3kg,439.00
847,35,49,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,4GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.3kg,639.00
855,803,17,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.2kg,745.00
911,1179,1313,Dell,Inspiron 3567,Notebook,15.6,1366x768,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,AMD Radeon R5 M430,Linux,2.3kg,805.99

In [283]:
df['TypeName'].value_counts()

TypeName
Notebook              522
Gaming                138
Ultrabook             135
2 in 1 Convertible     85
Workstation            18
Netbook                14
Name: count, dtype: int64

In [284]:
df['ScreenResolution'].value_counts()

ScreenResolution
Full HD 1920x1080                                346
1366x768                                         208
IPS Panel Full HD 1920x1080                      163
IPS Panel Full HD / Touchscreen 1920x1080         37
Full HD / Touchscreen 1920x1080                   32
Touchscreen 1366x768                              15
1600x900                                          11
IPS Panel 4K Ultra HD 3840x2160                   10
4K Ultra HD / Touchscreen 3840x2160                8
Quad HD+ / Touchscreen 3200x1800                   8
IPS Panel 4K Ultra HD / Touchscreen 3840x2160      8
IPS Panel Retina Display 2304x1440                 6
IPS Panel 1366x768                                 5
IPS Panel Retina Display 2560x1600                 5
4K Ultra HD 3840x2160                              5
IPS Panel Quad HD+ / Touchscreen 3200x1800         4
IPS Panel Touchscreen 2560x1440                    4
Touchscreen 2560x1440                              4
IPS Panel Touchscreen 1920x1200                    4
Touchscreen 2256x1504                              3
IPS Panel 2560x1440                                3
IPS Panel Retina Display 2880x1800                 3
1920x1080                                          3
Touchscreen 2400x1600                              2
2560x1440                                          2
IPS Panel Touchscreen / 4K Ultra HD 3840x2160      2
1440x900                                           2
Quad HD+ 3200x1800                                 2
IPS Panel Quad HD+ 2560x1440                       1
IPS Panel Full HD 2160x1440                        1
Touchscreen / Full HD 1920x1080                    1
Touchscreen / 4K Ultra HD 3840x2160                1
IPS Panel Quad HD+ 3200x1800                       1
IPS Panel Full HD 1920x1200                        1
IPS Panel Touchscreen 1366x768                     1
Name: count, dtype: int64

In [285]:
df[df['ScreenResolution'] == 'Full HD 1920x1080']

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
2,353,966,Toshiba,Portege Z30-C-1CW,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.2kg,1460.00
6,1136,60,Asus,X541UA-DM1897 (i3-6006U/4GB/256GB/FHD/Linux),Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,256GB SSD,Intel HD Graphics 520,Linux,2kg,415.00
7,609,1157,MSI,GP62M 7RDX,Gaming,15.6,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1050,Windows 10,2.4kg,1142.80
11,904,79,Dell,Inspiron 5570,Notebook,15.6,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,8GB,128GB SSD + 1TB HDD,Intel UHD Graphics 620,Windows 10,2.02kg,855.00
25,829,41,Asus,X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux),Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,1TB HDD,Intel HD Graphics 620,Linux,2kg,389.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894,4,1284,HP,Pavilion 15-AW003nv,Notebook,15.6,Full HD 1920x1080,AMD A9-Series 9410 2.9GHz,6GB,1.0TB Hybrid,AMD Radeon R7 M440,Windows 10,2.04kg,549.99
895,1134,709,Lenovo,IdeaPad 320-15AST,Notebook,15.6,Full HD 1920x1080,AMD A9-Series 9420 2.9GHz,4GB,256GB SSD,AMD Radeon 530,Windows 10,2.2kg,399.00
898,1187,1094,HP,Probook 650,Notebook,15.6,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,500GB HDD,Intel HD Graphics 520,Windows 7,2.31kg,940.00
908,716,1018,Toshiba,Portege Z30-C-16H,Notebook,13.3,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.2kg,1195.00
910,891,965,Dell,Latitude 7480,Ultrabook,14.0,Full HD 1920x1080,Intel Core i7 7600U 2.8GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.36kg,1775.00

In [286]:
df['Cpu'].value_counts()

Cpu
Intel Core i5 7200U 2.5GHz              142
Intel Core i7 7700HQ 2.8GHz             102
Intel Core i7 7500U 2.7GHz               88
Intel Core i5 8250U 1.6GHz               54
Intel Core i5 6200U 2.3GHz               51
                                       ...
Intel Pentium Quad Core N3700 1.6GHz      1
AMD A6-Series A6-9220 2.5GHz              1
AMD A9-Series 9420 2.9GHz                 1
AMD A6-Series 9220 2.9GHz                 1
AMD E-Series 9000 2.2GHz                  1
Name: count, Length: 104, dtype: int64

In [287]:
df[df['Cpu'] == 'Intel Core i5 7200U 2.5GHz']

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
17,718,332,Acer,Aspire E5-575,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,6GB,1TB HDD,Intel HD Graphics 620,Windows 10,2.23kg,549.0
26,1129,741,Acer,Extensa EX2540-58KR,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,Windows 10,2.4kg,559.0
27,1197,983,Lenovo,IdeaPad 310-15IKB,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,6GB,256GB SSD,Nvidia GeForce 920MX,Windows 10,2.4kg,695.0
29,233,323,HP,ProBook 640,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.95kg,980.0
52,192,720,Dell,Vostro 5568,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,1TB HDD,Intel HD Graphics 620,Linux,1.98kg,726.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,254,1264,Dell,Latitude 5480,Notebook,14.0,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,Windows 10,1.6kg,875.0
887,19,654,Acer,Swift 3,Ultrabook,14.0,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel Graphics 620,Windows 10,1.8kg,919.0
889,339,460,Lenovo,ThinkPad T470,Notebook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.65kg,1345.0
897,137,196,Xiaomi,Mi Notebook,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Nvidia GeForce MX150,No OS,1.3kg,999.9
902,793,576,Lenovo,ThinkPad L470,Notebook,14.0,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,Windows 10,2.02kg,990.0

In [288]:
df['Ram'].value_counts()

Ram
8GB     434
4GB     274
16GB    125
6GB      32
2GB      16
12GB     15
32GB     14
24GB      2
Name: count, dtype: int64

In [289]:
df['Memory'].value_counts()

Memory
256GB SSD                        293
1TB HDD                          150
500GB HDD                        100
512GB SSD                         75
128GB SSD +  1TB HDD              61
128GB SSD                         56
256GB SSD +  1TB HDD              52
32GB Flash Storage                27
2TB HDD                           11
64GB Flash Storage                11
512GB SSD +  1TB HDD              10
1TB SSD                            9
256GB Flash Storage                7
1.0TB Hybrid                       7
32GB SSD                           5
180GB SSD                          5
256GB SSD +  2TB HDD               4
16GB Flash Storage                 4
16GB SSD                           3
512GB SSD +  2TB HDD               2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
512GB Flash Storage                2
128GB Flash Storage                2
256GB SSD +  1.0TB Hybrid          1
64GB SSD                           1
240GB SSD                          1
256GB SSD +  256GB SSD             1
8GB SSD                            1
64GB Flash Storage +  1TB HDD      1
1.0TB HDD                          1
1TB HDD +  1TB HDD                 1
512GB SSD +  512GB SSD             1
128GB SSD +  2TB HDD               1
32GB HDD                           1
512GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [290]:
df['Gpu'].head(20)

0             AMD Radeon R7 M445
1          Intel HD Graphics 505
2          Intel HD Graphics 520
3        Nvidia GeForce GTX 1070
4          Intel HD Graphics 520
5        Nvidia GeForce GT 940MX
6          Intel HD Graphics 520
7        Nvidia GeForce GTX 1050
8           Nvidia GeForce 940MX
9     Nvidia GeForce GTX 1050 Ti
10         Intel HD Graphics 405
11        Intel UHD Graphics 620
12         Intel HD Graphics 520
13                AMD Radeon 530
14         Intel HD Graphics 510
15        Intel UHD Graphics 620
16         Intel HD Graphics 620
17         Intel HD Graphics 620
18          Nvidia Quadro M2200M
19          Nvidia GeForce MX150
Name: Gpu, dtype: object

In [291]:
df['OpSys'].value_counts()

OpSys
Windows 10      746
Linux            47
No OS            44
Windows 7        32
Chrome OS        20
macOS            11
Mac OS X          6
Windows 10 S      4
Android           2
Name: count, dtype: int64

In [292]:
df[df['OpSys']== 'Android']

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
414,452,1129,Lenovo,Yoga Book,2 in 1 Convertible,10.1,IPS Panel Touchscreen 1920x1200,Intel Atom x5-Z8550 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics 400,Android,0.69kg,549.0
833,1085,51,Lenovo,Yoga Book,2 in 1 Convertible,10.1,IPS Panel Touchscreen 1920x1200,Intel Atom x5-Z8550 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics 400,Android,0.69kg,319.0

In [293]:
df['Weight'].value_counts()

Weight
2.2kg     86
2.1kg     40
2.3kg     35
2.4kg     31
2kg       30
          ..
1.41kg     1
4kg        1
2.72kg     1
1.94kg     1
1.79kg     1
Name: count, Length: 158, dtype: int64

In [294]:
df['Weight'] = df['Weight'].str.replace('kg', '')
df['Weight']

0      2.36
1         2
2       1.2
3      4.42
4      1.26
       ...
907    1.25
908     1.2
909     2.4
910    1.36
911     2.3
Name: Weight, Length: 912, dtype: object

In [295]:
df['Weight'] = df['Weight'].astype(float)
df['Weight']

0      2.36
1      2.00
2      1.20
3      4.42
4      1.26
       ...
907    1.25
908    1.20
909    2.40
910    1.36
911    2.30
Name: Weight, Length: 912, dtype: float64

In [296]:
df['Weight'].describe()

count    912.000000
mean       2.032112
std        0.653772
min        0.690000
25%        1.500000
50%        2.040000
75%        2.300000
max        4.600000
Name: Weight, dtype: float64

In [297]:
df.isnull().sum()

id                  0
laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [331]:
import pandas as pd
import numpy as np
import re

# --- 1. FUNCIONES AUXILIARES (PARA V5) ---

def extract_cpu_model(cpu_text):
    """Agrupa los modelos de CPU por gama principal."""
    cpu_text = str(cpu_text)
    if 'Core i7' in cpu_text: return 'Core i7'
    if 'Core i5' in cpu_text: return 'Core i5'
    if 'Core i3' in cpu_text: return 'Core i3'
    if 'Ryzen 7' in cpu_text: return 'Ryzen 7'
    if 'Ryzen 5' in cpu_text: return 'Ryzen 5'
    if 'Ryzen 3' in cpu_text: return 'Ryzen 3'
    if re.search(r'AMD A\d+', cpu_text) or 'A-Series' in cpu_text: return 'AMD A-Series'
    if 'Pentium' in cpu_text: return 'Pentium'
    if 'Celeron' in cpu_text: return 'Celeron'
    if 'Atom' in cpu_text: return 'Atom'
    else: return 'Other' # Agrupamos los raros

def extract_gpu_series(gpu_text):
    """Agrupa las GPUs por serie principal."""
    gpu_text = str(gpu_text)
    if 'GeForce GTX' in gpu_text: return 'Nvidia GTX'
    if 'GeForce RTX' in gpu_text: return 'Nvidia RTX'
    if 'Quadro' in gpu_text: return 'Nvidia Quadro'
    if 'GeForce MX' in gpu_text: return 'Nvidia MX'
    if 'GeForce' in gpu_text: return 'Nvidia GeForce'
    if 'Radeon RX' in gpu_text: return 'AMD Radeon RX'
    if 'Radeon R' in gpu_text: return 'AMD Radeon R'
    if 'Radeon' in gpu_text: return 'AMD Radeon'
    if 'Iris' in gpu_text: return 'Intel Iris'
    if 'Intel HD' in gpu_text or 'Intel UHD' in gpu_text: return 'Intel HD/UHD'
    return 'Other' # Agrupamos los raros

# --- 2. FUNCIÓN PRINCIPAL DE LIMPIEZA (V5) ---

def preparar_datos_v5(data):
    """
    Función de limpieza V5 (Jerárquica/Agrupada)
    Esta es la que decidimos que era mejor.
    """
    df = data.copy()

    # --- Ram ---
    df['Ram'] = df['Ram'].str.replace('GB', '').astype(int)

    # --- Weight ---
    df['Weight'] = df['Weight'].str.replace('kg', '').astype(float).fillna(0)

    # --- ScreenResolution ---
    df['Inches'] = df['Inches'].fillna(0)
    df['ScreenResolution'] = df['ScreenResolution'].fillna('0x0')
    df['Touchscreen'] = df['ScreenResolution'].apply(lambda x: 1 if 'Touchscreen' in x else 0)
    df['IPS_Panel'] = df['ScreenResolution'].apply(lambda x: 1 if 'IPS' in x else 0)
    resolucion = df['ScreenResolution'].str.extract(r'(\d+)x(\d+)').fillna('0')
    df['X_Resolution'] = resolucion[0].astype(int)
    df['Y_Resolution'] = resolucion[1].astype(int)
    with np.errstate(divide='ignore', invalid='ignore'):
        df['PPI'] = (((df['X_Resolution']**2) + (df['Y_Resolution']**2))**0.5) / df['Inches']
    df['PPI'] = df['PPI'].replace([np.inf, -np.inf], 0).fillna(0)
    df.drop(['ScreenResolution', 'Inches', 'X_Resolution', 'Y_Resolution'], axis=1, inplace=True)

    # --- Cpu ---
    df['Cpu'] = df['Cpu'].fillna('')
    df['Cpu_Company'] = df['Cpu'].apply(lambda x: str(x).split()[0])
    df['Cpu_Speed_GHz'] = df['Cpu'].str.extract(r'(\d+\.?\d*)GHz').fillna(0).astype(float)
    df['Cpu_Model'] = df['Cpu'].apply(extract_cpu_model) # Usando Auxiliar 1
    df.drop('Cpu', axis=1, inplace=True)

    # --- Memory ---
    df['Memory'] = df['Memory'].fillna('')
    df['SSD_GB'] = 0; df['HDD_GB'] = 0; df['Flash_GB'] = 0; df['Hybrid_GB'] = 0
    df['SSD_GB'] = df['Memory'].str.extract(r'(\d+\.?\d*)\s*GB\s*SSD').fillna(0).astype(float)
    df['HDD_GB'] = df['Memory'].str.extract(r'(\d+\.?\d*)\s*GB\s*HDD').fillna(0).astype(float)
    df['Flash_GB'] = df['Memory'].str.extract(r'(\d+\.?\d*)\s*GB\s*Flash').fillna(0).astype(float)
    df['Hybrid_GB'] = df['Memory'].str.extract(r'(\d+\.?\d*)\s*GB\s*Hybrid').fillna(0).astype(float)
    df['SSD_TB'] = df['Memory'].str.extract(r'(\d+\.?\d*)\s*TB\s*SSD').fillna(0).astype(float)
    df['HDD_TB'] = df['Memory'].str.extract(r'(\d+\.?\d*)\s*TB\s*HDD').fillna(0).astype(float)
    df['Flash_TB'] = df['Memory'].str.extract(r'(\d+\.?\d*)\s*TB\s*Flash').fillna(0).astype(float)
    df['Hybrid_TB'] = df['Memory'].str.extract(r'(\d+\.?\d*)\s*TB\s*Hybrid').fillna(0).astype(float)
    df['SSD_GB'] = (df['SSD_GB'] + df['SSD_TB'] * 1024).astype(int)
    df['HDD_GB'] = (df['HDD_GB'] + df['HDD_TB'] * 1024).astype(int)
    df['Flash_GB'] = (df['Flash_GB'] + df['Flash_TB'] * 1024).astype(int)
    df['Hybrid_GB'] = (df['Hybrid_GB'] + df['Hybrid_TB'] * 1024).astype(int)
    # Eliminamos Total_Storage_GB (como decidimos)
    df.drop(['Memory', 'SSD_TB', 'HDD_TB', 'Flash_TB', 'Hybrid_TB'], axis=1, inplace=True)

    # --- Gpu ---
    df['Gpu'] = df['Gpu'].fillna('')
    df['Gpu_Company'] = df['Gpu'].apply(lambda x: str(x).split()[0])
    df['Gpu_Series'] = df['Gpu'].apply(extract_gpu_series) # Usando Auxiliar 2
    df['Gpu_Model_Num'] = df['Gpu'].str.extract(r'(\d{3,4})').fillna('Other') # Categórico
    df.drop('Gpu', axis=1, inplace=True)
    
    # --- Columnas irrelevantes ---
    if 'Product' in df.columns: df.drop('Product', axis=1, inplace=True)
    if 'laptop_ID' in df.columns: df.drop('laptop_ID', axis=1, inplace=True)
        
    # --- Rellenar NaNs ---
    num_cols = df.select_dtypes(include=np.number).columns
    df[num_cols] = df[num_cols].fillna(0)
    
    cat_cols_to_fill = ['Cpu_Company', 'Gpu_Company', 'OpSys', 'TypeName']
    for col in cat_cols_to_fill:
        if col in df.columns:
            df[col] = df[col].fillna('Unknown')
            if '' in df[col].unique():
                df[col] = df[col].replace('', 'Unknown')

    return df

# --- 3. APLICACIÓN DE LIMPIEZA Y CODIFICACIÓN (One-Hot Encoding) ---

# Cargar Datos
df_train = pd.read_csv('./data/train.csv')
df_test = pd.read_csv('./data/test.csv')

# Guardar ID de prueba y el Precio (target)
test_ids = df_test['id']
y = df_train['Price_euros'] # Esta será nuestra 'y'

# Quitar 'id' y 'Price_euros' ANTES de limpiar
df_train = df_train.drop(['id', 'Price_euros'], axis=1)
df_test = df_test.drop('id', axis=1)

# Aplicar la limpieza V5
print("Aplicando limpieza V5...")
df_train_limpio = preparar_datos_v5(df_train)
df_test_limpio = preparar_datos_v5(df_test)

# --- ESTE ES EL PASO NUEVO E IMPORTANTE: ONE-HOT ENCODING ---
print("Aplicando One-Hot Encoding...")

# Juntamos train y test temporalmente
# Esto asegura que CUALQUIER categoría (ej. 'Compañía') que solo
# exista en 'test' (o 'train') sea reconocida y se cree la columna.
df_full = pd.concat([df_train_limpio, df_test_limpio], axis=0)

# Aplicamos get_dummies para convertir todo el texto a 0s y 1s
# drop_first=True evita problemas de multicolinealidad (bueno para Reg. Lineal)
df_full_encoded = pd.get_dummies(df_full, drop_first=True)

# Separamos de nuevo
# 'X' (train) y 'X_test_final' (test) ya tienen EXACTAMENTE las mismas columnas
X = df_full_encoded.iloc[:len(df_train_limpio)]
X_test_final = df_full_encoded.iloc[len(df_train_limpio):]

# --- 4. RESULTADO ---
print("\n¡Preparación de datos completa!")
print(f"Forma de X (datos de entrenamiento): {X.shape}")
print(f"Forma de y (target): {y.shape}")
print(f"Forma de X_test_final (datos de prueba): {X_test_final.shape}")

print("\nEjemplo de X (entrenamiento) listo para el modelo:")
print(X.head())

Aplicando limpieza V5...
Aplicando One-Hot Encoding...

¡Preparación de datos completa!
Forma de X (datos de entrenamiento): (912, 117)
Forma de y (target): (912,)
Forma de X_test_final (datos de prueba): (391, 117)

Ejemplo de X (entrenamiento) listo para el modelo:
   Ram  Weight  Touchscreen  IPS_Panel         PPI  Cpu_Speed_GHz  SSD_GB  \
0    8    2.36            0          0  100.454670            2.7       0
1    4    2.00            0          0  100.454670            1.1       0
2    8    1.20            0          0  165.632118            2.3     256
3   16    4.42            0          1  282.423996            2.8     256
4    8    1.26            1          0  176.232574            2.4     256

   HDD_GB  Flash_GB  Hybrid_GB  ...  Gpu_Model_Num_860  Gpu_Model_Num_920  \
0    1024         0          0  ...              False              False
1    1024         0          0  ...              False              False
2       0         0          0  ...              False              False
3    1024         0          0  ...              False              False
4       0         0          0  ...              False              False

   Gpu_Model_Num_930  Gpu_Model_Num_940  Gpu_Model_Num_950  Gpu_Model_Num_960  \
0              False              False              False              False
1              False              False              False              False
2              False              False              False              False
3              False              False              False              False
4              False              False              False              False

   Gpu_Model_Num_965  Gpu_Model_Num_970  Gpu_Model_Num_980  \
0              False              False              False
1              False              False              False
2              False              False              False
3              False              False              False
4              False              False              False

   Gpu_Model_Num_Other
0                False
1                False
2                False
3                False
4                False

[5 rows x 117 columns]

C:\Users\Albert\AppData\Local\Temp\ipykernel_27332\1486288527.py:78: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Hybrid_GB'] = df['Memory'].str.extract(r'(\d+\.?\d*)\s*GB\s*Hybrid').fillna(0).astype(float)
C:\Users\Albert\AppData\Local\Temp\ipykernel_27332\1486288527.py:81: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Flash_TB'] = df['Memory'].str.extract(r'(\d+\.?\d*)\s*TB\s*Flash').fillna(0).astype(float)
C:\Users\Albert\AppData\Local\Temp\ipykernel_27332\1486288527.py:81: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Flash_TB'] = df['Memory'].str.extract(r'(\d+\.?\d*)\s*TB\s*Flash').fillna(0).astype(float)

In [332]:
X

,Ram,Weight,Touchscreen,IPS_Panel,PPI,Cpu_Speed_GHz,SSD_GB,HDD_GB,Flash_GB,Hybrid_GB,...,Gpu_Model_Num_860,Gpu_Model_Num_920,Gpu_Model_Num_930,Gpu_Model_Num_940,Gpu_Model_Num_950,Gpu_Model_Num_960,Gpu_Model_Num_965,Gpu_Model_Num_970,Gpu_Model_Num_980,Gpu_Model_Num_Other
0,8,2.36,0,0,100.454670,2.7,0,1024,0,0,...,False,False,False,False,False,False,False,False,False,False
1,4,2.00,0,0,100.454670,1.1,0,1024,0,0,...,False,False,False,False,False,False,False,False,False,False
2,8,1.20,0,0,165.632118,2.3,256,0,0,0,...,False,False,False,False,False,False,False,False,False,False
3,16,4.42,0,1,282.423996,2.8,256,1024,0,0,...,False,False,False,False,False,False,False,False,False,False
4,8,1.26,1,0,176.232574,2.4,256,0,0,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,4,1.25,1,1,135.094211,1.6,0,0,32,0,...,False,False,False,False,False,False,False,False,False,False
908,4,1.20,0,0,165.632118,2.3,128,0,0,0,...,False,False,False,False,False,False,False,False,False,False
909,8,2.40,0,0,100.454670,2.2,0,1024,0,0,...,False,False,False,False,False,False,False,False,False,True
910,8,1.36,0,0,157.350512,2.8,256,0,0,0,...,False,False,False,False,False,False,False,False,False,False
911,8,2.30,0,0,100.454670,2.7,0,1024,0,0,...,False,False,False,False,False,False,False,False,False,False

In [336]:
pd.set_option('display.max_columns', None)
X

,Ram,Weight,Touchscreen,IPS_Panel,PPI,Cpu_Speed_GHz,SSD_GB,HDD_GB,Flash_GB,Hybrid_GB,Company_Apple,Company_Asus,Company_Chuwi,Company_Dell,Company_Fujitsu,Company_Google,Company_HP,Company_Huawei,Company_LG,Company_Lenovo,Company_MSI,Company_Mediacom,Company_Microsoft,Company_Razer,Company_Samsung,Company_Toshiba,Company_Vero,Company_Xiaomi,TypeName_Gaming,TypeName_Netbook,TypeName_Notebook,TypeName_Ultrabook,TypeName_Workstation,OpSys_Chrome OS,OpSys_Linux,OpSys_Mac OS X,OpSys_No OS,OpSys_Windows 10,OpSys_Windows 10 S,OpSys_Windows 7,OpSys_macOS,Cpu_Company_Intel,Cpu_Company_Samsung,Cpu_Model_Atom,Cpu_Model_Celeron,Cpu_Model_Core i3,Cpu_Model_Core i5,Cpu_Model_Core i7,Cpu_Model_Other,Cpu_Model_Pentium,Gpu_Company_ARM,Gpu_Company_Intel,Gpu_Company_Nvidia,Gpu_Series_AMD Radeon R,Gpu_Series_AMD Radeon RX,Gpu_Series_Intel HD/UHD,Gpu_Series_Intel Iris,Gpu_Series_Nvidia GTX,Gpu_Series_Nvidia GeForce,Gpu_Series_Nvidia MX,Gpu_Series_Nvidia Quadro,Gpu_Series_Other,Gpu_Model_Num_1050,Gpu_Model_Num_1060,Gpu_Model_Num_1070,Gpu_Model_Num_1080,Gpu_Model_Num_1200,Gpu_Model_Num_130,Gpu_Model_Num_150,Gpu_Model_Num_2000,Gpu_Model_Num_2200,Gpu_Model_Num_3000,Gpu_Model_Num_315,Gpu_Model_Num_330,Gpu_Model_Num_360,Gpu_Model_Num_365,Gpu_Model_Num_385,Gpu_Model_Num_400,Gpu_Model_Num_405,Gpu_Model_Num_4190,Gpu_Model_Num_420,Gpu_Model_Num_430,Gpu_Model_Num_440,Gpu_Model_Num_445,Gpu_Model_Num_455,Gpu_Model_Num_460,Gpu_Model_Num_465,Gpu_Model_Num_500,Gpu_Model_Num_505,Gpu_Model_Num_510,Gpu_Model_Num_5130,Gpu_Model_Num_515,Gpu_Model_Num_520,Gpu_Model_Num_530,Gpu_Model_Num_5300,Gpu_Model_Num_540,Gpu_Model_Num_550,Gpu_Model_Num_555,Gpu_Model_Num_560,Gpu_Model_Num_580,Gpu_Model_Num_6000,Gpu_Model_Num_615,Gpu_Model_Num_6150,Gpu_Model_Num_620,Gpu_Model_Num_630,Gpu_Model_Num_640,Gpu_Model_Num_650,Gpu_Model_Num_860,Gpu_Model_Num_920,Gpu_Model_Num_930,Gpu_Model_Num_940,Gpu_Model_Num_950,Gpu_Model_Num_960,Gpu_Model_Num_965,Gpu_Model_Num_970,Gpu_Model_Num_980,Gpu_Model_Num_Other
0,8,2.36,0,0,100.454670,2.7,0,1024,0,0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,4,2.00,0,0,100.454670,1.1,0,1024,0,0,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,8,1.20,0,0,165.632118,2.3,256,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,16,4.42,0,1,282.423996,2.8,256,1024,0,0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,8,1.26,1,0,176.232574,2.4,256,0,0,0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,4,1.25,1,1,135.094211,1.6,0,0,32,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
908,4,1.20,0,0,165.632118,2.3,128,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
909,8,2.40,0,0,100.454670,2.2,0,1024,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
910,8,1.36,0,0,157.350512,2.8,256,0,0,0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
911,8,2.30,0,0,100.454670,2.7,0,1024,0,0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [304]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 912 entries, 0 to 911
Columns: 117 entries, Ram to Gpu_Model_Num_Other
dtypes: bool(107), float64(3), int64(7)
memory usage: 173.7 KB

In [329]:
import xgboost as xgb
import pandas as pd
from sklearn.model_selection import GridSearchCV

# Asumimos que X, y, X_test_final, y test_ids ya existen y están listos

# ==========================================================
# 1. DEFINIR MODELO Y PARÁMETROS
# ==========================================================

# Usamos el modelo que mejor funcionó (el que optimiza MSE por defecto)
# ya que dio el MAE más bajo (177.40)
xgb_base = xgb.XGBRegressor(
    objective='reg:squarederror',
    random_state=42,
    n_jobs=-1
)

# Definimos el "Grid" (la rejilla) de parámetros a probar.
# ¡CUIDADO! Esto es exhaustivo.
param_grid = {
    'max_depth': [4, 5, 6],           # Profundidad del árbol (alrededor de 5)
    'learning_rate': [0.01, 0.05, 0.1], # Tasa de aprendizaje
    'n_estimators': [500, 1000],        # Número de árboles
    'subsample': [0.8, 1.0],            # Muestra de datos por árbol
    'colsample_bytree': [0.8, 1.0]      # Muestra de características por árbol
}

# Total de combinaciones: 3 * 3 * 2 * 2 * 2 = 72 modelos
# Total de entrenamientos (con cv=3): 72 * 3 = 216 entrenamientos

# ==========================================================
# 2. CONFIGURAR Y EJECUTAR GRIDSEARCHCV
# ==========================================================
grid_search = GridSearchCV(
    estimator=xgb_base,
    param_grid=param_grid,
    scoring='neg_mean_absolute_error', # <--- ¡CLAVE! Optimiza para MAE
    cv=3,                                # 3-fold cross-validation
    verbose=2,                           # Muestra el progreso
    n_jobs=-1                            # Usa todos los núcleos
)

print("Iniciando GridSearchCV... Esto puede tardar MUCHO tiempo.")
# Entrenamos la búsqueda sobre el conjunto de entrenamiento COMPLETO
grid_search.fit(X, y)

# ==========================================================
# 3. MOSTRAR LOS MEJORES RESULTADOS
# ==========================================================
print("\n¡Búsqueda completada!")
print(f"Mejores parámetros encontrados: {grid_search.best_params_}")

# El 'best_score_' será negativo (ej. -175.5).
# Lo multiplicamos por -1 para ver el MAE real en positivo.
best_mae = -grid_search.best_score_

print(f"\nMejor MAE (promedio de CV): {best_mae:.2f}")
print(f"MAE anterior (manual): 177.40")

# ==========================================================
# 4. GENERAR SUMISIÓN CON EL MEJOR MODELO
# ==========================================================

# grid_search automáticamente re-entrena el mejor modelo (best_estimator_)
# con todos los datos, así que podemos usarlo directamente.
best_model = grid_search.best_estimator_

print("\nGenerando predicciones para Kaggle con el modelo optimizado...")
preds_test_final = best_model.predict(X_test_final)

# Crear el archivo
submission_grid = pd.DataFrame({
    'id': test_ids,
    'Price_euros': preds_test_final
})

submission_grid.to_csv('submission_xgb_gridsearch.csv', index=False)
print("¡Archivo 'submission_xgb_gridsearch.csv' creado!")

Iniciando GridSearchCV... Esto puede tardar MUCHO tiempo.
Fitting 3 folds for each of 72 candidates, totalling 216 fits

¡Búsqueda completada!
Mejores parámetros encontrados: {'colsample_bytree': 1.0, 'learning_rate': 0.05, 'max_depth': 4, 'n_estimators': 1000, 'subsample': 0.8}

Mejor MAE (promedio de CV): 166.25
MAE anterior (manual): 177.40

Generando predicciones para Kaggle con el modelo optimizado...
¡Archivo 'submission_xgb_gridsearch.csv' creado!

In [ ]:
# ============================================
# RESUMEN DEL WORKFLOW DE KAGGLE
# ============================================

# Este notebook sigue el flujo de trabajo estándar de una competición de Kaggle:

# 1. CARGA DE DATOS
#    - Cargar train.csv, test.csv y sample_submission.csv

# 2. EXPLORACIÓN Y ANÁLISIS
#    - Visualizar datos con .head(), .info()
#    - Analizar correlaciones y distribuciones

# 3. PREPROCESAMIENTO
#    - Limpiar datos (eliminar texto innecesario, convertir tipos)
#    - Tratar valores faltantes si los hay

# 4. SELECCIÓN DE FEATURES
#    - Decidir qué variables usar en el modelo
#    - Realizar feature engineering si es necesario

# 5. DIVISIÓN TRAIN/TEST
#    - Separar datos para entrenamiento y validación
#    - Nunca entrenar con datos de test

# 6. ENTRENAMIENTO DEL MODELO
#    - Elegir un algoritmo (en este caso LinearRegression)
#    - Entrenar con los datos de entrenamiento

# 7. EVALUACIÓN
#    - Medir el rendimiento con métricas (R², MAE, RMSE)
#    - Validar que el modelo generaliza bien

# 8. PREDICCIONES
#    - Aplicar el modelo al conjunto de test
#    - Generar las predicciones finales

# 9. SUBMISSION
#    - Preparar el archivo en el formato correcto
#    - Enviar a Kaggle y revisar la puntuación